classes:
  - nsidc_miniconda

# Note, this used to install `bumpversion`, but that clashes w/ the base
# env. Users should create their own env w/ necessary dev deps manually.
nsidc_miniconda::install:
  /opt/miniconda:
    version: '23.7.4'
    owner: vagrant
    group: vagrant
    build: false
    config:
      location: /home/vagrant
      channels:
        anaconda_nsidc_main: true
        anaconda_nsidc_dev: true
        conda_forge: true

nsidc_nfs::sharemounts:
  /share/apps/hermes-all:
    project: apps
    share: hermes
  /share/apps/hermes-orders-all:
    project: appdata
    share: hermes-orders
  /share/logs/hermes-all:
    project: logs
    share: hermes
