forge "https://forgeapi.puppetlabs.com"

# Module for creating NSIDC Jenkins servers
mod "nsidc/nsidc_jenkins",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git",
  :ref => 'latest'

mod "nsidc/nsidc_miniconda",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-miniconda.git",
  :ref => 'latest'

mod 'jfryman/nginx'
mod 'willdurand/nodejs'
