forge "https://forgeapi.puppetlabs.com"

# Vault client module
mod "nsidc/nsidc_vault_client",
  :git => "git@bitbucket.org:nsidc/puppet-nsidc-vault-client.git",
  :ref => 'puppet7'

mod "nsidc/nsidc_nfs",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git",
  :ref => "latest"

mod "puppetlabs/vcsrepo"
mod 'puppetlabs-docker'
