forge "https://forgeapi.puppetlabs.com"

# Module for creating NSIDC Jenkins servers
mod "nsidc/nsidc_jenkins",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git",
  :ref => 'latest'

mod "garethr/docker"